### ISSUE TITLE
Without optional -e parameter, default /data/ is not carrying over to sync script

### ISSUE THREAD

**Issue by andymotta** [istepanov/docker-backup-to-s3#3]

**Comment by edasque** [comment]
FYI @andymotta & @istepanov I see the same issue.

`DATA_PATH=${DATA_PATH:-/data/}` doesn't work, probably because it's not readable by / exported to the sync.sh process.

**Comment by edasque** [comment]
Fixed in https://github.com/istepanov/docker-backup-to-s3/commit/7eef9363d683bfa4bac8e6353d8da4d7e80895ba I imagine.

**Comment by istepanov** [comment]
@edasque yes, I should have mentioned it here
